// HUB-H1-AC-06 · HUB-FR-89 · C2: `bun run contracts:gen|contracts:check` (plan H1 §2.6, ADR-0009).
// gen: zod → hub.schema.json → pydantic (datamodel-code-generator, chạy trong container qua run.ts).
// check: sinh vào thư mục tạm cạnh repo (mount được), so byte với bản commit, rồi chạy mẫu hai phía.
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { run } from "../../apps/agent-runtime/scripts/run";
import { hubJsonSchemaBundle } from "../../packages/contracts/src/hub/json-schema";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const APP = join(ROOT, "apps/agent-runtime");
const SCHEMA_REL = "contracts/hub.schema.json";
const PY_REL = "src/agent_runtime/contracts/hub.py";
const HEADER =
  "# GENERATED by `bun run contracts:gen` from packages/contracts/src/hub — DO NOT EDIT.";

const CODEGEN = [
  "uv run datamodel-codegen --input-file-type jsonschema --output-model-type pydantic_v2.BaseModel",
  "--target-python-version 3.12 --use-annotated --field-constraints --extra-fields forbid",
  "--enum-field-as-literal all --disable-timestamp --use-double-quotes",
  `--custom-file-header '${HEADER}'`,
].join(" ");

/** `pattern` kèm `format` uuid/date-time làm pydantic ném TypeError: bỏ pattern, giữ format. */
function stripFormatPatterns(n: unknown): void {
  if (Array.isArray(n)) {
    for (const x of n) stripFormatPatterns(x);
    return;
  }
  if (typeof n !== "object" || n === null) return;
  const o = n as Record<string, unknown>;
  if (o.format === "uuid" || o.format === "date-time") o.pattern = undefined;
  for (const v of Object.values(o)) stripFormatPatterns(v);
}

/** Nội dung hub.schema.json: bỏ `$schema`/`$id` lặp trong từng def, 2 dấu cách, xuống dòng cuối. */
export function schemaText(): string {
  const b = hubJsonSchemaBundle();
  const defs = b.$defs as Record<string, Record<string, unknown>>;
  for (const d of Object.values(defs)) {
    d.$schema = undefined;
    d.$id = undefined;
  }
  stripFormatPatterns(defs);
  return `${JSON.stringify(b, null, 2)}
`;
}

/** Sinh schema + pydantic vào `outRel` (tương đối apps/agent-runtime). Trả exit code. */
export function generate(outRel: string): number {
  const dir = join(APP, outRel);
  mkdirSync(join(dir, "contracts"), { recursive: true });
  mkdirSync(join(dir, "py"), { recursive: true });
  writeFileSync(join(dir, SCHEMA_REL), schemaText());
  // biome ci (lefthook) đòi JSON đúng định dạng của repo: sinh xong format luôn để byte ổn định.
  const fmt0 = Bun.spawnSync(
    [
      "bunx",
      "biome",
      "format",
      "--write",
      "--no-errors-on-unmatched",
      "--files-ignore-unknown=true",
      join(dir, SCHEMA_REL),
    ],
    { cwd: ROOT },
  );
  if (fmt0.exitCode !== 0) return fmt0.exitCode ?? 1;
  const schema = `${outRel}/${SCHEMA_REL}`;
  const py = `${outRel}/py/hub.py`;
  const fmt = `uv run ruff check --fix-only --quiet ${py}; uv run ruff format --quiet ${py}`;
  return run(
    `uv sync --frozen 2>/dev/null || uv sync; ${CODEGEN} --input ${schema} --output ${py} && ${fmt}`,
  );
}

function same(a: string, b: string): boolean {
  return existsSync(a) && existsSync(b) && readFileSync(a, "utf8") === readFileSync(b, "utf8");
}

function check(): number {
  const tmpRel = ".contracts-check-tmp";
  const tmp = join(APP, tmpRel);
  rmSync(tmp, { recursive: true, force: true });
  try {
    const rc = generate(tmpRel);
    if (rc !== 0) return rc;
    const ok =
      same(join(tmp, SCHEMA_REL), join(APP, SCHEMA_REL)) &&
      same(join(tmp, "py/hub.py"), join(APP, PY_REL));
    if (!ok) {
      console.error(
        "contracts:check — hub.schema.json/hub.py lệch zod; chạy `bun run contracts:gen`.",
      );
      return 1;
    }
    return run(
      "uv run pytest -q src/agent_runtime/contracts tests/acceptance/test_contracts_hub.py",
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function gen(): number {
  const rc = generate(".contracts-gen-tmp");
  const tmp = join(APP, ".contracts-gen-tmp");
  try {
    if (rc !== 0) return rc;
    mkdirSync(join(APP, "contracts"), { recursive: true });
    mkdirSync(join(APP, "src/agent_runtime/contracts"), { recursive: true });
    writeFileSync(join(APP, SCHEMA_REL), readFileSync(join(tmp, SCHEMA_REL)));
    writeFileSync(join(APP, PY_REL), readFileSync(join(tmp, "py/hub.py")));
    return 0;
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

if (import.meta.main) {
  const cmd = process.argv[2];
  if (cmd !== "gen" && cmd !== "check") {
    console.error("dùng: bun tools/contracts-gen/hub.ts gen|check");
    process.exit(2);
  }
  const rc = cmd === "gen" ? gen() : check();
  if (rc === 0 && cmd === "check") {
    const t = Bun.spawnSync(
      [
        "bun",
        "test",
        "tests/acceptance/H1/rules/contracts-hub.test.ts",
        "packages/contracts/src/hub",
      ],
      { cwd: ROOT, stdout: "inherit", stderr: "inherit" },
    );
    process.exit(t.exitCode ?? 1);
  }
  process.exit(rc);
}
