/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedMemberRouteImport } from './routes/_authed/member'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedAccountPasswordRouteImport } from './routes/_authed/account.password'
import { Route as AuthedTenantsIndexRouteImport } from './routes/_authed/tenants/index'
import { Route as AuthedTenantsTenantIdRouteImport } from './routes/_authed/tenants/$tenantId'
import { Route as AuthedTenantsNewRouteImport } from './routes/_authed/tenants/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMemberRoute = AuthedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountPasswordRoute = AuthedAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantsIndexRoute = AuthedTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantsTenantIdRoute = AuthedTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantsNewRoute = AuthedTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof AuthedMemberRoute
  '/users': typeof AuthedUsersRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/tenants/$tenantId': typeof AuthedTenantsTenantIdRoute
  '/tenants/new': typeof AuthedTenantsNewRoute
  '/tenants/': typeof AuthedTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof AuthedMemberRoute
  '/users': typeof AuthedUsersRoute
  '/': typeof AuthedIndexRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/tenants/$tenantId': typeof AuthedTenantsTenantIdRoute
  '/tenants/new': typeof AuthedTenantsNewRoute
  '/tenants': typeof AuthedTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_authed/member': typeof AuthedMemberRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/account/password': typeof AuthedAccountPasswordRoute
  '/_authed/tenants/$tenantId': typeof AuthedTenantsTenantIdRoute
  '/_authed/tenants/new': typeof AuthedTenantsNewRoute
  '/_authed/tenants/': typeof AuthedTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/member'
    | '/users'
    | '/account/password'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/member'
    | '/users'
    | '/'
    | '/account/password'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/tenants'
  id:
    | '__root__'
    | '/_authed'
    | '/change-password'
    | '/login'
    | '/_authed/member'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/account/password'
    | '/_authed/tenants/$tenantId'
    | '/_authed/tenants/new'
    | '/_authed/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/member': {
      id: '/_authed/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthedMemberRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/password': {
      id: '/_authed/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthedAccountPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants/': {
      id: '/_authed/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthedTenantsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants/$tenantId': {
      id: '/_authed/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthedTenantsTenantIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants/new': {
      id: '/_authed/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof AuthedTenantsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedMemberRoute: typeof AuthedMemberRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountPasswordRoute: typeof AuthedAccountPasswordRoute
  AuthedTenantsTenantIdRoute: typeof AuthedTenantsTenantIdRoute
  AuthedTenantsNewRoute: typeof AuthedTenantsNewRoute
  AuthedTenantsIndexRoute: typeof AuthedTenantsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMemberRoute: AuthedMemberRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountPasswordRoute: AuthedAccountPasswordRoute,
  AuthedTenantsTenantIdRoute: AuthedTenantsTenantIdRoute,
  AuthedTenantsNewRoute: AuthedTenantsNewRoute,
  AuthedTenantsIndexRoute: AuthedTenantsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
