/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedOrchestratorRouteImport } from './routes/_authed/orchestrator'
import { Route as AuthedAgentsIndexRouteImport } from './routes/_authed/agents.index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrchestratorRoute = AuthedOrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsIndexRoute = AuthedAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/orchestrator': typeof AuthedOrchestratorRoute
  '/agents/': typeof AuthedAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/orchestrator': typeof AuthedOrchestratorRoute
  '/': typeof AuthedIndexRoute
  '/agents': typeof AuthedAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/orchestrator': typeof AuthedOrchestratorRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/agents/': typeof AuthedAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orchestrator' | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to: '/orchestrator' | '/' | '/agents'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/orchestrator'
    | '/_authed/'
    | '/_authed/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orchestrator': {
      id: '/_authed/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof AuthedOrchestratorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/': {
      id: '/_authed/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAgentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedOrchestratorRoute: typeof AuthedOrchestratorRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAgentsIndexRoute: typeof AuthedAgentsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrchestratorRoute: AuthedOrchestratorRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAgentsIndexRoute: AuthedAgentsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
