/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedCIdRouteImport } from './routes/_authed/c.$id'
import { Route as AuthedCNewRouteImport } from './routes/_authed/c.new'
import { Route as AuthedRoomsIdRouteImport } from './routes/_authed/rooms.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCIdRoute = AuthedCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCNewRoute = AuthedCNewRouteImport.update({
  id: '/c/new',
  path: '/c/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsIdRoute = AuthedRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/c/$id': typeof AuthedCIdRoute
  '/c/new': typeof AuthedCNewRoute
  '/rooms/$id': typeof AuthedRoomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/c/$id': typeof AuthedCIdRoute
  '/c/new': typeof AuthedCNewRoute
  '/rooms/$id': typeof AuthedRoomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/c/$id': typeof AuthedCIdRoute
  '/_authed/c/new': typeof AuthedCNewRoute
  '/_authed/rooms/$id': typeof AuthedRoomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/c/$id' | '/c/new' | '/rooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/c/$id' | '/c/new' | '/rooms/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/c/$id'
    | '/_authed/c/new'
    | '/_authed/rooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/c/$id': {
      id: '/_authed/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AuthedCIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/c/new': {
      id: '/_authed/c/new'
      path: '/c/new'
      fullPath: '/c/new'
      preLoaderRoute: typeof AuthedCNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/$id': {
      id: '/_authed/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof AuthedRoomsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCIdRoute: typeof AuthedCIdRoute
  AuthedCNewRoute: typeof AuthedCNewRoute
  AuthedRoomsIdRoute: typeof AuthedRoomsIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCIdRoute: AuthedCIdRoute,
  AuthedCNewRoute: AuthedCNewRoute,
  AuthedRoomsIdRoute: AuthedRoomsIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
