# GENERATED by `bun run contracts:gen` from packages/contracts/src/hub — DO NOT EDIT.
# pyright: reportInvalidTypeForm=false

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class Model(RootModel[Any]):
    root: Any


class AgentTypeKey(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]


class Tool(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9-]{2,32}$")]


class Mcp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[str, Field(max_length=2048, min_length=1, pattern="^https?:\\/\\/")]
    tools: Annotated[list[Tool], Field(max_length=20, min_length=1)]


class Agent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    key: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]
    role: Literal["orchestrator", "agent"]


class Model1(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class ProfileStep(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    provider_key: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]
    model: Model1 | None
    on: Annotated[list[Literal["error", "quota", "timeout"]], Field(max_length=3)]


class HistoryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["user", "assistant"]
    content: Annotated[str, Field(max_length=64000)]


class RunEvent1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    at: AwareDatetime
    type: Literal["job.started"]
    worker_id: Annotated[str, Field(max_length=64, min_length=1)]
    provider_key: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]


class Percent(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=100)]


class RunEvent2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    at: AwareDatetime
    type: Literal["job.progress"]
    message: Annotated[str, Field(max_length=200, min_length=1)]
    percent: Percent | None


class Output1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["text"]
    text: Annotated[str, Field(max_length=64000)]


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_tokens: Annotated[int, Field(ge=0, le=9007199254740991)]
    output_tokens: Annotated[int, Field(ge=0, le=9007199254740991)]


class RunEvent4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    at: AwareDatetime
    type: Literal["job.failed"]
    status: Literal["failed", "cancelled", "timed_out"]
    code: Literal[
        "ALL_PROVIDERS_EXHAUSTED",
        "TIMEOUT",
        "CANCELLED",
        "UPSTREAM_ERROR",
        "INTERNAL_ERROR",
        "NOT_CONFIGURED",
    ]
    reason: (
        Literal[
            "quota",
            "tenant_slots",
            "provider_busy",
            "provider_unavailable",
            "orphaned",
            "crash",
            "cancelled",
            "timeout",
            "invalid_payload",
            "invalid_output",
            "sandbox",
            "credential",
            "upstream",
            "refused",
            "attachment",
        ]
        | None
    )
    message: Annotated[str, Field(max_length=500, min_length=1)]
    usage: Usage


class RunEvent5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    at: AwareDatetime
    type: Literal["job.delta"]
    kind: Literal["answer", "done", "partial"]
    text: Annotated[str, Field(max_length=4000, min_length=1)]


class AgentResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["done"]
    text: Annotated[str, Field(max_length=64000, min_length=1)]


class AgentResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["partial"]
    text: Annotated[str, Field(max_length=64000, min_length=1)]
    missing: Annotated[str, Field(max_length=2000, min_length=1)]


class Choice(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class AgentResult3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["need_input"]
    question: Annotated[str, Field(max_length=2000, min_length=1)]
    choices: Annotated[list[Choice], Field(max_length=6)]


class AgentResult(RootModel[AgentResult1 | AgentResult2 | AgentResult3]):
    root: AgentResult1 | AgentResult2 | AgentResult3


class OrchestratorDecision1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision: Literal["delegate"]
    agent: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]
    task: Annotated[str, Field(max_length=8000, min_length=1)]


class OrchestratorDecision2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision: Literal["answer"]
    text: Annotated[str, Field(max_length=64000, min_length=1)]


class OrchestratorDecision3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision: Literal["ask"]
    question: Annotated[str, Field(max_length=2000, min_length=1)]
    choices: Annotated[list[Choice], Field(max_length=6)]


class OrchestratorDecision(
    RootModel[OrchestratorDecision1 | OrchestratorDecision2 | OrchestratorDecision3]
):
    root: OrchestratorDecision1 | OrchestratorDecision2 | OrchestratorDecision3


class Description(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vi: Annotated[str, Field(max_length=400, min_length=1)]
    en: Annotated[str, Field(max_length=400, min_length=1)]


class AgentTypeManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]
    runtime: Literal["agentic-cli", "llm", "python"]
    description: Description
    config_schema: dict[str, Any]
    version: Annotated[int, Field(ge=1, le=9007199254740991)]


class JobEnqueuedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    provider_key: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]


class JobCancelPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    run_id: UUID


class HubConfigChangedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    version: Annotated[int, Field(ge=1, le=9007199254740991)]


class Inputs(RootModel[str]):
    root: Annotated[str, Field(max_length=64000)]


class Inputs1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["image", "document"]
    transfer_method: Literal["local_file"]
    upload_file_id: Annotated[str, Field(max_length=100, min_length=1)]


class Query(RootModel[str]):
    root: Annotated[str, Field(max_length=16000, min_length=1)]


class OutputField(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class JobPayloadWorkflowAsync(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    type: Literal["workflow.async"]
    provider_key: Literal["dify"]
    job_id: UUID
    run_id: UUID
    step_id: UUID
    tenant_id: UUID
    user_id: UUID
    conversation_id: UUID
    flow_id: UUID
    workflow_id: UUID
    feature_id: UUID | None
    command_id: UUID | None
    workflow_key: Annotated[str, Field(pattern="^[a-z0-9-]{2,32}$")]
    app_type: Literal["workflow", "chat", "agent"]
    inputs: dict[
        constr(pattern=r"^[A-Za-z_][A-Za-z0-9_]{0,63}$"),
        Inputs | float | bool | Inputs1,
    ]
    query: Query | None
    output_field: OutputField | None
    dify_user: Annotated[str, Field(max_length=200, min_length=1)]
    side_effect: bool
    timeout_s: Annotated[int, Field(ge=1, le=600)]


class DifyCredentialResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_url: Annotated[str, Field(max_length=2048, min_length=1, pattern="^https?:\\/\\/")]
    api_key: Annotated[str, Field(max_length=2048, min_length=1)]
    app_type: Literal["workflow", "chat", "agent"]


class JobOutputResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID


class JobAttachment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    name: Annotated[
        str,
        Field(
            max_length=120,
            min_length=1,
            pattern="^[^./\\\\\\x00-\\x1f\\x7f-][^/\\\\\\x00-\\x1f\\x7f]*$",
        ),
    ]
    mime: Literal[
        "application/pdf",
        "image/png",
        "image/jpeg",
        "image/gif",
        "image/webp",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "text/plain",
        "text/markdown",
        "text/csv",
        "application/xml",
        "application/json",
    ]
    size: Annotated[int, Field(ge=1, le=20971520)]
    sha256: Annotated[str, Field(pattern="^[0-9a-f]{64}$")]


class JobPayload1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    type: Literal["agent.cli"]
    runtime: Literal["agentic-cli"]
    job_id: UUID
    run_id: UUID
    step_id: UUID
    tenant_id: UUID
    user_id: UUID
    conversation_id: UUID
    flow_id: UUID
    feature_id: UUID | None
    agent_type_key: AgentTypeKey | None
    mcp: Mcp | None
    agent: Agent
    provider_key: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{1,47}$")]
    model: Model1 | None
    step_index: Annotated[int, Field(ge=0, le=4)]
    max_turns: Annotated[int, Field(ge=1, le=100)]
    profile_steps: Annotated[list[ProfileStep], Field(max_length=5, min_length=1)]
    system_prompt: Annotated[str, Field(max_length=20000)]
    prompt: Annotated[str, Field(max_length=200000, min_length=1)]
    history: Annotated[list[HistoryItem], Field(max_length=50)]
    use_session: bool
    allowed_tools: Annotated[list[Literal["Read", "Grep", "Glob", "Write"]], Field(max_length=4)]
    output: Literal["agent_result", "text"]
    timeout_s: Annotated[int, Field(ge=10, le=3600)]
    stream: bool | None = None
    attachments: Annotated[list[JobAttachment] | None, Field(max_length=10)] = None


class JobPayload(RootModel[JobPayload1 | JobPayloadWorkflowAsync]):
    root: JobPayload1 | JobPayloadWorkflowAsync


class Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["agent_result"]
    result: AgentResult


class RunEvent3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    job_id: UUID
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    at: AwareDatetime
    type: Literal["job.result"]
    output: Output | Output1
    usage: Usage
    session_resumed: bool
    outputs: Annotated[list[UUID] | None, Field(max_length=5, min_length=1)] = None


class RunEvent(RootModel[RunEvent1 | RunEvent2 | RunEvent3 | RunEvent4 | RunEvent5]):
    root: RunEvent1 | RunEvent2 | RunEvent3 | RunEvent4 | RunEvent5
